version: '3.8'

services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: task-manager-app
    ports:
      - "5000:5000"
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring

  node-exporter:
    image: prom/node-exporter:latest
    ports:
      - "9100:9100"
    networks:
      - monitoring

  fail2ban:
    image: crazymax/fail2ban:latest
    restart: always
    environment:
      - TZ=UTC
    volumes:
      - ./fail2ban:/data
    ports:
      - "8080:8080"
    networks:
      - monitoring

  iptables-exporter:
    image: "cloudflare/iptables-exporter:latest"
    ports:
      - "9120:9120"  # Porta para o Prometheus acessar métricas
    networks:
      - monitoring