global:
  scrape_interval: 15s  # Intervalo de coleta

scrape_configs:
  - job_name: "flask_app"
    static_configs:
      - targets: ["flask-app:5000"]  # Nome do serviço definido no docker-compose

  - job_name: "node_exporter"
    static_configs:
      - targets: ["node-exporter:9100"]  # Nome do serviço do node-exporter