name: CI/CD Pipeline

on:
  push:
    branches: ["master", "development"]
  pull_request:
     branches: ["master", "development"]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          pip install --upgrade -r requirements.txt
