name: CI/CD Pipeline

on:
  push:
    branches: ["master", "development"]
  pull_request:
    branches: ["master", "development"]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade -r requirements.txt

  test:
    needs: build
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -r requirements.txt

      - name: Run unit test
        run: |
          pytest
        continue-on-error: true

  sast:
    needs: build
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install Bandit
        run: |
          python -m pip install bandit

      - name: Run Bandit SAST
        run: |
          bandit -r . -f html -o bandit_report.html || true

      - name: Upload Bandit Report
        uses: actions/upload-artifact@v3
        with:
          name: bandit-report
          path: bandit_report.html

  dependency-check:
    needs: build
    runs-on: ubuntu-24.04

    steps:
      - name: Check out code
        uses: actions/upload-artifact@v3
      
      - name: Install OWASP Dependency-Check
        run: |
            wget https://github.com/jeremylong/DependencyCheck/releases/download/v10.0.4/dependency-check-10.0.4-release.zip
            unzip dependency-check-10.0.4-release.zip
            sudo mv dependency-check/bin/dependency-check.sh /usr/local/bin/dependency-check
            sudo chmod +x /usr/local/bin/dependency-check

    - name: Run OWASP Dependency Check
      run: |
        /usr/local/bin/dependency-check --project "Task-Manager-using-Flask" -o ./dependency-check-report --scan . --exclude "**/*.dll" --exclude "**/*.exe" || true

    - name: Upload Dependency Check Report
      uses: actions/upload-artifact@v3
      with:
        name: dependency-check-report
        path: ./dependency-check-report
