name: CI/CD Pipeline

on:
  push:
    branches: ["master", "development"]
  pull_request:
    branches: ["master", "development"]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade -r requirements.txt

test:
  needs: build
  runs-on: ubuntu-24.04

  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -r requirements.txt;

    - name: Run unit test
      run: |
        pytest
      continue-on-error: true
sast:
  runs-on: ubuntu-24.04
  needs: build

  steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: "3.9"

    - name: Install Bandit
      run: |
        python -m pip install bandit

    - name: Run Bandit SAST
      run: |
        bandit -r . -f html -o bandit_report.html || true

    # Publica o relatório do Bandit como um artefato
    - name: Upload Bandit Report
      uses: actions/upload-artifact@v3
      with:
        name: bandit-report
        path: bandit_report.html
      run: |
        bandit -r . -f txt -o bandit_report.txt
